### ISSUE TITLE
add user settings

### ISSUE THREAD

**Issue by WickyNilliams** [jfromaniello/sublime-node-require#11]
Currently, you have to edit the package's settings to change to double quotes. This would be better in a separate user settings file (otherwise it will get overwritten on update?).

**Comment by jfromaniello** [comment]
Yes, I agree

**Comment by WickyNilliams** [comment]
Not sure if something has changed, but this seems to work now. I was able to add a file and modify settings in User space

**Comment by jfromaniello** [comment]
@WickyNilliams Hello!

Just for the prosperity, this is what I do now:

![](https://dl.dropbox.com/s/sfmjvt2mz3asl3t/ss-2016-08-31T09-31-45.png?dl=0)


Then, this is my config:

```javascript
{
	"quotes_type": "simple",
	"source_js_new_line": "const {0} = require({1});"
}
```

It will be nice to be able to configure this per project basis.

**Comment by WickyNilliams** [comment]
Yes, exactly like that :)

There might be a way to have it per project. I know sublime has an order which it consults settings files, and project level settings is in the list somewhere. See: https://www.sublimetext.com/docs/2/settings.html
